//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *VGPUClaim) DeepCopyInto(out *VGPUClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VGPUClaim) DeepCopy() *VGPUClaim {
	if in == nil {
		return nil
	}
	out := new(VGPUClaim)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VGPUClaimList) DeepCopyInto(out *VGPUClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VGPUClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VGPUClaimList) DeepCopy() *VGPUClaimList {
	if in == nil {
		return nil
	}
	out := new(VGPUClaimList)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// VGPUClaimSpec contains only value types (int64, string, ServiceTier) — plain copy suffices.
func (in *VGPUClaimSpec) DeepCopyInto(out *VGPUClaimSpec) {
	*out = *in
}

func (in *VGPUClaimSpec) DeepCopy() *VGPUClaimSpec {
	if in == nil {
		return nil
	}
	out := new(VGPUClaimSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUClaimStatus) DeepCopyInto(out *VGPUClaimStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VGPUClaimStatus) DeepCopy() *VGPUClaimStatus {
	if in == nil {
		return nil
	}
	out := new(VGPUClaimStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUSlice) DeepCopyInto(out *VGPUSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VGPUSlice) DeepCopy() *VGPUSlice {
	if in == nil {
		return nil
	}
	out := new(VGPUSlice)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VGPUSliceList) DeepCopyInto(out *VGPUSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VGPUSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VGPUSliceList) DeepCopy() *VGPUSliceList {
	if in == nil {
		return nil
	}
	out := new(VGPUSliceList)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// VGPUSliceSpec contains only value types (int64, string) — plain copy suffices.
func (in *VGPUSliceSpec) DeepCopyInto(out *VGPUSliceSpec) {
	*out = *in
}

func (in *VGPUSliceSpec) DeepCopy() *VGPUSliceSpec {
	if in == nil {
		return nil
	}
	out := new(VGPUSliceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VGPUSliceStatus) DeepCopyInto(out *VGPUSliceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VGPUSliceStatus) DeepCopy() *VGPUSliceStatus {
	if in == nil {
		return nil
	}
	out := new(VGPUSliceStatus)
	in.DeepCopyInto(out)
	return out
}
