replicaCount: 1

image:
  repository: pranav2910/vgpu-scheduler
  pullPolicy: IfNotPresent
  tag: "latest"

nodeAgent:
  enabled: true
  image:
    repository: pranav2910/vgpu-nodeagent
    tag: "latest"

telemetry:
  serviceMonitor:
    enabled: true
  grafanaDashboard:
    enabled: true
