name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Run Unit Tests
      run: go test -v ./...
    - name: Run Fuzz Tests
      run: go test -fuzz=FuzzBinPack -fuzztime=10s ./test/fuzz
